### PR TITLE
Created qoyyuum.html

### PR DESCRIPTION
**Pull request by Qoyyuum**
Let's be friends!

### CODE REVIEW

**Comment by RaidAndFade** [comment]
Please make sure to include a link your GITHUB URL in your HTML file

**Comment by Qoyyuum** [comment]
I did. Line 16. As a button.

**Comment by RaidAndFade** [comment]
Yes i noticed the button to your gitpages, you could have kept that if you wanted. You just need to have the url to your actual github profile visible somewhere on the page

**Comment by RaidAndFade** [comment]
Ill give this pr some time in case you want to change the button back and add a seconary link (which would probably make us both happier)

**Comment by RaidAndFade** [comment]
Lovrly, thanks.

**Pull request merged**
