### PR TITLE
Added RGB color guessing game

### PR DESCRIPTION
**Pull request by saxenanamay**
Previous entry of this game is not working due to incorrectly linked js and css files.

### CODE REVIEW

**Comment by RaidAndFade** [comment]
Which one is the previous entry? Would it be alright if you simply PR'd a fix for that one instead? (i know that's against the rules but the rule is more towards people randomly changing other people's games, if it's a legitimate fix i'll allow it)

**Comment by RaidAndFade** [comment]
Your pull request seems good, but must be checked by a human maintainer for the following reason(s):
1. These submissions must be checked manually because of the potential complexity of submissions, if you've reached this point in the process you're most likely a valid submission.

Please be patient until a maintainer has time to look over your contribution.

***This is an automated response, beep boop.
if you think there is a mistake, contact a maintainer***
> fa32c6d9afdc6ddb0563e51e05d8dc4f44c6961c

**Comment by saxenanamay** [comment]
Sure, take a look at games/Rahul-Vijay
His css and js files have the wrong names and hence it is not working.

**Comment by RaidAndFade** [comment]
This request's code has changed since approval. Re-Judging contents...
Your pull request seems good, but must be checked by a human maintainer for the following reason(s):
1. This PR modifies one or more pre-existing files.

Please be patient until a maintainer has time to look over your contribution.

***This is an automated response, beep boop.
if you think there is a mistake, contact a maintainer***
> 7ea5d58a7abefafc91a7c9831b701937d893cb44

**Comment by RaidAndFade** [comment]
Perfect. Thanks

**Pull request merged**
