### PR TITLE
what's up my dudes

### PR DESCRIPTION
**Pull request by drakantas**
hi

### CODE REVIEW

**Comment by RaidAndFade** [comment]
Your pull request seems good, but must be checked by a human maintainer for the following reason(s):
1. This contains potentially hazardous tags that need manual review.

Please be patient until a maintainer has time to look over your contribution.

***This is an automated response, beep boop.
if you think there is a mistake, contact a maintainer***
> 226e1e9d46bb58a04937a99c58d970df42555c52

**Comment by RaidAndFade** [comment]
Looks good to me! Lets get this in!

**Comment by RaidAndFade** [comment]
Also just realized this is #100, Two days and 100 prs, this better be a record or something

**Comment by drakantas** [comment]
def didn't time it

**Pull request merged**
