### PR TITLE
Added cassianomon.html on Friends

### PR DESCRIPTION
**Pull request by cassianomon**

### CODE REVIEW

**Comment by RaidAndFade** [comment]
Your pull request seems good, but must be checked by a human maintainer for the following reason(s):
1. Your file potentially has references to foul language.
2. This contains potentially hazardous tags that need manual review.

Please be patient until a maintainer has time to look over your contribution.

***This is an automated response, beep boop.
if you think there is a mistake, contact a maintainer***
> 1f0b24d8efe4317bb7ec89856d00e5260fd6b5eb

**Comment by RaidAndFade** [comment]
Why would you import a FONT as base64. Use a cdn link or something

**Comment by cassianomon** [comment]
> Why would you import a FONT as base64. Use a cdn link or something

solved

**Comment by RaidAndFade** [comment]
Your pull request seems good, but must be checked by a human maintainer for the following reason(s):
1. This contains potentially hazardous tags that need manual review.

Please be patient until a maintainer has time to look over your contribution.

***This is an automated response, beep boop.
if you think there is a mistake, contact a maintainer***
> 26cc503ab5db33a68a0d8efb8393bdfe1ce38b66

**Comment by RaidAndFade** [comment]
Yeah there's nothing wrong with using b64 for images and raw-data but i've honestly never seen it used for a font so it kinda shocked me, especially since most/all fonts typically are cdn'd somewhere

**Pull request merged**
