### PR TITLE
sudoku_game

### PR DESCRIPTION
**Pull request by rrhythmsharma**
I have made a sudoku game using html, js and css. The game has 3 levels, easy, medium and hard, Please accept my contibition.

### CODE REVIEW

**Comment by rrhythmsharma** [comment]
sir i have added main.js, main.css and if my path and folder name is not correct then suggest me the right name and path

**Comment by RaidAndFade** [comment]
Your pull request needs further work because of the following reason(s):
1. You have a file at Games/Sudoku_game, this is not allowed.
2. You have a file at Games/Sudoku_game, this is not allowed.
3. You have a file at Games/Sudoku_game, this is not allowed.
4. Your `main.js` file was not found, it is a requirement (even if empty)
5. Your `main.css` file was not found, it is a requirement (even if empty)
6. Your `index.html` file was not found, this one should exist and be nonempty

Once you have resolved the issues, **comment on this request to be re-judged**

***This is an automated response, beep boop.
if you think there is a mistake, contact a maintainer***
> 627ddf0d7e43741e9c39350cef51e796684ea1ba

**Comment by RaidAndFade** [comment]
Your folder name should be `Games/rrhythmsharma`. It says this very clearly more than once in the instructions.

**Comment by RaidAndFade** [comment]
This PR has been idle for more than 24 hours, and will now be closed. Feel free to re-open.

***This is an automated response, beep boop.
if you think there is a mistake, contact a maintainer***
> 627ddf0d7e43741e9c39350cef51e796684ea1ba

**Pull request closed without merging**
