### PR TITLE
Happy Hacktoberfest

### PR DESCRIPTION
**Pull request by sr229**
nya

### CODE REVIEW

**Comment by RaidAndFade** [comment]
Your pull request is currently considered invalid for the following reason(s):
1. Your filename must be `sr229.html`
2. Your file does not clearly show a link to your github profile.

Once you have resolved the issues, comment on this request to be re-judged

***This is an automated response, beep boop.
if you think there is a mistake, contact a maintainer***
> 20c6aac3bb5420e0b912b13bf81e707b0d44583f

**Comment by drakantas** [comment]
self plug

**Comment by RaidAndFade** [comment]
Your pull request seems good, but must be checked by a human maintainer for the following reason(s):
1. This contains potentially hazardous tags that need manual review.

Please be patient until a maintainer has time to look over your contribution.

***This is an automated response, beep boop.
if you think there is a mistake, contact a maintainer***
> 9ca9439ec9cc0578e5068f451741f5c5ef8c9aea

**Comment by RaidAndFade** [comment]
Please make the link optional rather than meta refresh

**Comment by RaidAndFade** [comment]
This request's code has changed since approval. Re-Judging contents...
Your pull request looks good, and is ready for merging!

Thank you for being a part of Open Source, I hope you continue to help other repositories in the future!

***This is an automated response, beep boop.
if you think there is a mistake, contact a maintainer***
> 8beb9812fa41d76424cb827fe0bb9e24bbd753be

**Pull request merged**
