### PR TITLE
Sudoku_game

### PR DESCRIPTION
**Pull request by rrhythmsharma**
I have made a sudoku  game using html, js and css. The game has 3 levels, easy, medium and hard, Please accept my contibition.

### CODE REVIEW

**Comment by rrhythmsharma** [comment]
i am uploading js and css files  ↓
                                                      
[sudoku_js_css.zip](https://github.com/RaidAndFade/Hacktoberfest2018/files/2476137/sudoku_js_css.zip)

**Comment by RaidAndFade** [comment]
Your pull request seems good, but must be checked by a human maintainer for the following reason(s):
1. Your file is not in a project folder ("Friends", "Games"). This may be intentional, but most likely not.

Please be patient until a maintainer has time to look over your contribution.

***This is an automated response, beep boop.
if you think there is a mistake, contact a maintainer***
> 44038ce4ab1c4d5d6f18f111c77bdef9bc2cf662

**Comment by rrhythmsharma** [comment]
The path was changed by mistake, now  The mistake has improved

**Comment by RaidAndFade** [comment]
This request's code has changed since approval. Re-Judging contents...
Your pull request needs further work because of the following reason(s):
1. You added/changed/deleted 1 files. You can only add three (3) files `index.html` `main.js` `main.css`.
2. You have a file at Games/Rhythm_Sudoku, this is not allowed.
3. Your `main.js` file was not found, it is a requirement (even if empty)
4. Your `main.css` file was not found, it is a requirement (even if empty)
5. Your `index.html` file was not found, this one should exist and be nonempty

Once you have resolved the issues, **comment on this request to be re-judged**

***This is an automated response, beep boop.
if you think there is a mistake, contact a maintainer***
> b5feb7e750177fd40b85e1177da03149e134d8e5

**Comment by rrhythmsharma** [comment]
Request re-judge

sir i have added main.js, main.css and if my path and folder name is not correct then suggest me the right name and path

**Pull request closed without merging**
