### PR TITLE
added html

### PR DESCRIPTION
**Pull request by jduell12**

### CODE REVIEW

**Comment by jduell12** [comment]
I finished with week 1 and went on to week 2 and started working on week 2 project before I realized I didn't as for a pull request for week one. So the pull request shows multiple files because I'm working on the week 2 challenge (interactive game with an index.html, main.js and main.css).

**Comment by RaidAndFade** [comment]
Your pull request needs further work because of the following reason(s):
1. More than one file has been added/removed/modified.

Once you have resolved the issues, **comment on this request to be re-judged**

***This is an automated response, beep boop.
if you think there is a mistake, contact a maintainer***
> 32f7274877e75231d873439287878516360a56fe

**Comment by RaidAndFade** [comment]
You made modifications to files in README. this is not a part of any challenge. Remove those two files and i will be happy to merge

**Comment by jduell12** [comment]
I'm sorry I didn't realize I saved filed to the README. I removed those files and made sure all the files are where they should be. Everything should be good now. If not let me know!

**Comment by RaidAndFade** [comment]
You have a file "games/.../untitled-1" please remove this file.

**Comment by RaidAndFade** [comment]
I

**Comment by RaidAndFade** [comment]
Sorry about that. Im looking through these on my phone and its hard to press the tiny buttons.

**Comment by RaidAndFade** [comment]
Your pull request needs further work because of the following reason(s):
1. More than one file has been added/removed/modified.

Once you have resolved the issues, **comment on this request to be re-judged**

***This is an automated response, beep boop.
if you think there is a mistake, contact a maintainer***
> db8d965bfa7cd10b5c766c037b096fb619b6b8d2

**Comment by jduell12** [comment]
I removed that file! No worries! I appreciate your feedback and apologize for the files showing up in random areas. I'll make sure when I finish week 2 that I double check all files and changes I've made so there's no untitled files anywhere or in the wrong place.

**Comment by RaidAndFade** [comment]
Looks good for now, ill keep this pr here under attention (rather than needs work) until your game is completed. Basically preventing the bot from autoclosing

**Comment by RaidAndFade** [comment]
This PR has been idle for more than 24 hours, and will now be closed. Feel free to re-open.

***This is an automated response, beep boop.
if you think there is a mistake, contact a maintainer***
> 58064ca03a93aecf9c22db2e5723c782cd34ac46

**Comment by RaidAndFade** [comment]
Whenever you've completed the challenge either open a new PR, or tell me to reopen this one for you.

**Pull request closed without merging**
