### PR TITLE
Joined to the friends list

### PR DESCRIPTION
**Pull request by Odatha**
Joined to the friends list..

### CODE REVIEW

**Comment by RaidAndFade** [comment]
Your pull request needs further work because of the following reason(s):
1. Your filename must be `Odatha.html`

Once you have resolved the issues, **comment on this request to be re-judged**

***This is an automated response, beep boop.
if you think there is a mistake, contact a maintainer***
> f5c443ef1730c0b5d983ffb0b726985739c9b221

**Comment by Odatha** [comment]
rename the html file

**Comment by RaidAndFade** [comment]
Your pull request needs further work because of the following reason(s):
1. More than one file has been added/removed/modified.

Once you have resolved the issues, **comment on this request to be re-judged**

***This is an automated response, beep boop.
if you think there is a mistake, contact a maintainer***
> 517a0ef143d98464c5ce7006cf9c56177cbc2d26

**Comment by RaidAndFade** [comment]
Remove "Friends/Odprofile.html" and i will merge

**Comment by RaidAndFade** [comment]
This PR has been idle for more than 24 hours, and will now be closed. Feel free to re-open.

***This is an automated response, beep boop.
if you think there is a mistake, contact a maintainer***
> 705517e66b85aa1fb80c936439336758b170dc94

**Pull request closed without merging**
