### PR TITLE
new game added

### PR DESCRIPTION
**Pull request by nitinrohra**

### CODE REVIEW

**Comment by RaidAndFade** [comment]
Your pull request seems good, but must be checked by a human maintainer for the following reason(s):
1. The bot does not support marking the week2 challenge yet

Please be patient until a maintainer has time to look over your contribution.

***This is an automated response, beep boop.
if you think there is a mistake, contact a maintainer***
> b0ef90430ba8cfb4af1ec2b20f5a3493f1d27adf

**Comment by RaidAndFade** [comment]
`main.js`
`main.css`
follow the rules.

**Comment by nitinrohra** [comment]
changes done @RaidAndFade

**Comment by RaidAndFade** [comment]
Your pull request seems good, but must be checked by a human maintainer for the following reason(s):
1. The bot does not support marking the week2 challenge yet

Please be patient until a maintainer has time to look over your contribution.

***This is an automated response, beep boop.
if you think there is a mistake, contact a maintainer***
> fb87bff934131b6cdef84c6cb4aedde904b82cf3

**Pull request merged**
