### PR TITLE
Added:bounce eater game,name to contributors.md

### PR DESCRIPTION
**Pull request by 11A11**

### CODE REVIEW

**Comment by RaidAndFade** [comment]
Please remove extra "README.md" file from games folder and rename `main-finished.js` to `main.js`

**Comment by 11A11** [comment]
Done as requested! Removed the README.md, and renamed main-finished.js to main.js.

**Comment by RaidAndFade** [comment]
Forgot to mention your style.css must be main.css. after that I can merge :)

**Comment by 11A11** [comment]
Changed the style.css to main.css :)

**Pull request merged**
