### PR TITLE
added ribrah77 folder and a PONG game

### PR DESCRIPTION
**Pull request by ribrah77**

### CODE REVIEW

**Comment by RaidAndFade** [comment]
Your pull request needs further work because of the following reason(s):
1. Your `main.js` file was not found, it is a requirement (even if empty)
2. Your `main.css` file was not found, it is a requirement (even if empty)

Once you have resolved the issues, **comment on this request to be re-judged**

***This is an automated response, beep boop.
if you think there is a mistake, contact a maintainer***
> b4cfc4a8ad9f507231bbcecb87f0a758aae13324

**Comment by ribrah77** [comment]
I believe theres a mistake, I added an empty main.js and an empty main css files in Games/ribrah77

**Comment by ribrah77** [comment]
Ive added an empty main.js and an empty main.css, requesting a re-judging

**Comment by RaidAndFade** [comment]
Your pull request seems good, but must be checked by a human maintainer for the following reason(s):
1. Your HTML file potentially has references to foul language.
2. These submissions must be checked manually because of the potential complexity of submissions, if you've reached this point in the process you're most likely a valid submission.

Please be patient until a maintainer has time to look over your contribution.

***This is an automated response, beep boop.
if you think there is a mistake, contact a maintainer***
> 0b9c7c0f690c9ff2fb71b5c91df73be0390b745b

**Pull request merged**
