### PR TITLE
ryanc16 - Created Halloween memory matching game

### PR DESCRIPTION
**Pull request by ryanc16**

### CODE REVIEW

**Comment by RaidAndFade** [comment]
Your pull request seems good, but must be checked by a human maintainer for the following reason(s):
1. The bot does not support marking the week2 challenge yet

Please be patient until a maintainer has time to look over your contribution.

***This is an automated response, beep boop.
if you think there is a mistake, contact a maintainer***
> 897168ad7bd10096308ea449a6e71e70bd43fbb8

**Comment by RaidAndFade** [comment]
Looks good, can't check functionallity right now so im assuming you have. merging, if you find that there are bugs feel free to PR again and it will be merged.

**Comment by RaidAndFade** [comment]
Checked it out, looks to me like it works. Thanks! Fun game.

**Comment by ryanc16** [comment]
Thanks! glad you like it. I did find a small bug however, so ill make another pull request.

**Pull request merged**
