### PR TITLE
Added 'worleyd.html' to Friends directory

### PR DESCRIPTION
**Pull request by WorleyD**

### CODE REVIEW

**Comment by WorleyD** [comment]
Fixed

**Comment by WorleyD** [comment]
Fixed Fixed. My bad.

**Comment by RaidAndFade** [comment]
um....
now you've put the link in the page title. it needs to be on the page.

**Comment by WorleyD** [comment]
...I did not know that wasn't allowed. Moved it. Fixed Fixed Fixed

**Comment by RaidAndFade** [comment]
good enough, thanks.

**Pull request merged**
