### PR TITLE
thanks raid

### PR DESCRIPTION
**Pull request by cakedan**

### CODE REVIEW

**Comment by RaidAndFade** [comment]
first of all... #222. nice. 

your pr contains nsfw content (derogatory terms). please fix that.

**Comment by RaidAndFade** [comment]
Your pull request seems good, but must be checked by a human maintainer for the following reason(s):
1. This contains potentially hazardous tags that need manual review.

Please be patient until a maintainer has time to look over your contribution.

***This is an automated response, beep boop.
if you think there is a mistake, contact a maintainer***
> 3dbeee7635b026ecc0992f1e46c57bd9229e377f

**Comment by RaidAndFade** [comment]
Your pull request seems good, but must be checked by a human maintainer for the following reason(s):
1. Your file potentially has references to bad language.
2. This contains potentially hazardous tags that need manual review.

Please be patient until a maintainer has time to look over your contribution.

***This is an automated response, beep boop.
if you think there is a mistake, contact a maintainer***
> 3dbeee7635b026ecc0992f1e46c57bd9229e377f

**Comment by cakedan** [comment]
DONE

**Comment by RaidAndFade** [comment]
This request's code has changed since approval. Re-Judging contents...
Your pull request seems good, but must be checked by a human maintainer for the following reason(s):
1. This contains potentially hazardous tags that need manual review.

Please be patient until a maintainer has time to look over your contribution.

***This is an automated response, beep boop.
if you think there is a mistake, contact a maintainer***
> 3d6cd0729b3115f0969bfafa08497dc24438b1a0

**Pull request merged**
