### PR TITLE
Added myself

### PR DESCRIPTION
**Pull request by TheNoodleMoose**

### CODE REVIEW

**Comment by RaidAndFade** [comment]
Your pull request needs further work because of the following reason(s):
1. Your file does not clearly show a link to your github profile.

Once you have resolved the issues, **comment on this request to be re-judged**

***This is an automated response, beep boop.
if you think there is a mistake, contact a maintainer***
> 8e9a46181a17a2ca16bba488a0599e8f83789aca

**Comment by TheNoodleMoose** [comment]
Added my Github Link!

**Comment by RaidAndFade** [comment]
Your pull request seems good, but must be checked by a human maintainer for the following reason(s):
1. This contains potentially hazardous tags that need manual review.

Please be patient until a maintainer has time to look over your contribution.

***This is an automated response, beep boop.
if you think there is a mistake, contact a maintainer***
> 90a432e9518dd5f1b13fd30dbd50e0e26c7bebe4

**Comment by RaidAndFade** [comment]
Your link needs to be clearly visible on the page, not in a comment.

**Comment by TheNoodleMoose** [comment]
Fixed it, sorry about that!

**Comment by RaidAndFade** [comment]
Thanks!

**Pull request merged**
