### PR TITLE
Create SloRunner.html

### PR DESCRIPTION
**Pull request by SloRunner**

### CODE REVIEW

**Comment by RaidAndFade** [comment]
Your pull request needs further work because of the following reason(s):
1. Your file has a github link but it's (probably) not to your profile.

Once you have resolved the issues, **comment on this request to be re-judged**

***This is an automated response, beep boop.
if you think there is a mistake, contact a maintainer***
> 30e61c4945d81b352b9bed862ce023604f425641

**Comment by SloRunner** [comment]
updated it

**Comment by RaidAndFade** [comment]
Your pull request needs further work because of the following reason(s):
1. Your file has a github link but it's (probably) not to your profile.

Once you have resolved the issues, **comment on this request to be re-judged**

***This is an automated response, beep boop.
if you think there is a mistake, contact a maintainer***
> 895e219e89ca12da6b1f61f95f4bdd9f4e7d6e6f

**Comment by RaidAndFade** [comment]
Looks fine, the bot can't tell from image to link.

**Comment by SloRunner** [comment]
so should i change it to imgur or something?

**Comment by SloRunner** [comment]
it should work now

**Comment by RaidAndFade** [comment]
Oh crap my wifi cut out and i didnt merge. No no theres nothing wrong with ue file its the bot that cant tell

**Pull request merged**
