### PR TITLE
Inspired by tutorial at http://www.lostdecadegames.com/how-to-make-a-…

### PR DESCRIPTION
**Pull request by MartinSeibert**
…simple-html5-canvas-game/

### CODE REVIEW

**Comment by RaidAndFade** [comment]
Your pull request needs further work because of the following reason(s):
1. Your `main.css` file was not found, it is a requirement (even if empty)

Once you have resolved the issues, **comment on this request to be re-judged**

***This is an automated response, beep boop.
if you think there is a mistake, contact a maintainer***
> 3d40d8c3ffe42d064b4284bf04b90eeb1b9c7f9a

**Comment by MartinSeibert** [comment]
Can any maintainers comment on this? My fork that this PR references has a main.css although it is empty. And I see the addition of the main.css in the commit that it references. Did I do something wrong?

**Comment by RaidAndFade** [comment]
Nah the bot's dumb, i'd fix it but honestly this challenge is over today anyways so it's nbd. your submission is good.

**Comment by MartinSeibert** [comment]
Thanks!

**Pull request merged**
