### PR TITLE
Add another snake game

### PR DESCRIPTION
**Pull request by januridp**
Add another snake game

### CODE REVIEW

**Comment by RaidAndFade** [comment]
Your pull request seems good, but must be checked by a human maintainer for the following reason(s):
1. The bot does not support marking the week2 challenge yet

Please be patient until a maintainer has time to look over your contribution.

***This is an automated response, beep boop.
if you think there is a mistake, contact a maintainer***
> 8422c47d86d7b61d088ac6afc789ee6db19eb8bd

**Comment by RaidAndFade** [comment]
Please import p5.js from an external CDN or something similar, you're only allowed to have `main.js` as your js file.

**Comment by januridp** [comment]
please review again 👍

**Comment by RaidAndFade** [comment]
Your pull request seems good, but must be checked by a human maintainer for the following reason(s):
1. The bot does not support marking the week2 challenge yet

Please be patient until a maintainer has time to look over your contribution.

***This is an automated response, beep boop.
if you think there is a mistake, contact a maintainer***
> de54d657ab806e9c9fb8bd4b0f07a3bf15ab5b45

**Comment by RaidAndFade** [comment]
Love it! Thanks!

**Comment by januridp** [comment]
Could I do it now or after all challenges?
what are your plans for the next challenge?
will this challenge last for 5 weeks?

**Comment by RaidAndFade** [comment]
You can do it whenever you'd like.
There's no specific plan for next week but the project will be maintained at least until oct31, and there are ideas between maintainers as to what to do each week. 
The project is going to be up indefinitely, along with the challenges, but it's only going to be maintained and PRs will only be merged daily until oct31. After that I plan on keeping the project open to contributions but most likely will not check it nearly as often.

**Pull request merged**
