### PR TITLE
Once again my profile card

### PR DESCRIPTION
**Pull request by Simply007**
Your automatic detection did not detect button to my profile #189.

So I have added another one that is more visible. Hope the check pass.

### CODE REVIEW

**Comment by Simply007** [comment]
OK,
I am sorry my fault, but how to open the old pull request. I don't see anything in the UI, how to reopen it:
image

**Comment by RaidAndFade** [comment]
Oh, you pulled from the same branch again. Yeah nevermind, i'll just merge this one.

**Comment by Simply007** [comment]
Yeap. Thanks!

You can label the previous one with `invalid` label. It won't be count on the hacktoberfest stats:

You can check it here:
* https://hacktoberfest.digitalocean.com/stats/Simply007

**Comment by RaidAndFade** [comment]
Nah, thats fine. you seem like a nice guy, no need to punish you for a mistake (especially one thats partially my fault)

**Pull request merged**
