### PR TITLE
Sogastar.html

### PR DESCRIPTION
**Pull request by Sogastar**

### CODE REVIEW

**Comment by RaidAndFade** [comment]
Your pull request needs further work because of the following reason(s):
1. Your filename must be `Sogastar.html`
2. Your file does not have the `.html` extension.

Once you have resolved the issues, **comment on this request to be re-judged**

***This is an automated response, beep boop.
if you think there is a mistake, contact a maintainer***
> 6ad3db71d9ff1afe73077e48fc1a69c5f1cf7f9c

**Comment by Sogastar** [comment]
Hi, i changed filename

**Comment by RaidAndFade** [comment]
No you changed the PR title.

**Comment by RaidAndFade** [comment]
Your pull request seems good, but must be checked by a human maintainer for the following reason(s):
1. This contains potentially hazardous tags that need manual review.

Please be patient until a maintainer has time to look over your contribution.

***This is an automated response, beep boop.
if you think there is a mistake, contact a maintainer***
> d0e10e57e849816bf2a352cebe61a242a0368800

**Pull request merged**
