### PR TITLE
Improved Front Page

### PR DESCRIPTION
**Pull request by lazycipher**

### CODE REVIEW

**Comment by lazycipher** [comment]
@RaidAndFade  you can tell me if you want any change !! I'll cancel this PR and will create new!

**Comment by RaidAndFade** [comment]
So... few minor changes and then i'll merge. 
1. The page title (and the in-page text) should be "Hacktoberfest" as one word, not "Hacktober fest"
2. I'd love if the "fork" button was rather a "Join" function that linked to the README.md

**Comment by lazycipher** [comment]
I've got the 1st point!
Can you please elaborate 2nd point little more !

**Comment by RaidAndFade** [comment]
So, instead of having the option to directly fork, they should be required to read the README.md first, 

Basically make the button link to the README.md, and have the text be "join the list!" or something similar

**Comment by lazycipher** [comment]
Okay!! Got the second point too!
I was thinking to add a logo of "Hacktoberfest" instead of text and for that I'll need to create a directory with name /images

Is this okay ?

**Comment by RaidAndFade** [comment]
I'd like to keep the file as one file, so if you want to you can use the BASE64 image embedded into the file, but i'd rather not have extra files. (you could also just \ with the remote url on their website to be honest)

**Comment by RaidAndFade** [comment]
Love it! Thanks!

**Pull request merged**
