### PR TITLE
tafique:added html file

### PR DESCRIPTION
**Pull request by tafique**

### CODE REVIEW

**Comment by RaidAndFade** [comment]
Your pull request needs further work because of the following reason(s):
1. Your file does not clearly show a link to your github profile.

Once you have resolved the issues, **comment on this request to be re-judged**

***This is an automated response, beep boop.
if you think there is a mistake, contact a maintainer***
> 06956a3e088827667aedb679b0e4774c48e83078

**Comment by RaidAndFade** [comment]
You're referencing files and images that do not exist.

**Comment by tafique** [comment]
Check the updated file

**Comment by RaidAndFade** [comment]
Your pull request needs further work because of the following reason(s):
1. Less than one file has been added/removed/modified.

Once you have resolved the issues, **comment on this request to be re-judged**

***This is an automated response, beep boop.
if you think there is a mistake, contact a maintainer***
> 54858f8682b47944dd0ed26a0d44d3fb22cb5f36

**Comment by RaidAndFade** [comment]
Interesting. github doesn't want to show the .diff for this commit

**Comment by RaidAndFade** [comment]
Looks good either way, merging.

**Pull request merged**
